# Generated by Django 5.2.15 on 2026-06-15 16:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('RENT', '房租'), ('UTILITY', '水电'), ('MAINTENANCE', '维修'), ('PROPERTY', '物业')], max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dueDate', models.DateField()),
                ('paidDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', '待付'), ('PAID', '已付'), ('OVERDUE', '逾期'), ('WAIVED', '已减免')], default='PENDING', max_length=20)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='lease.lease')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
