# Generated by Django 5.2.15 on 2026-06-15 16:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=80)),
                ('entityType', models.CharField(max_length=40)),
                ('entityId', models.CharField(max_length=80)),
                ('oldValue', models.JSONField(blank=True, default=dict)),
                ('newValue', models.JSONField(blank=True, default=dict)),
                ('ipAddress', models.GenericIPAddressField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
