# Generated by Django 5.2.15 on 2026-06-15 16:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('type', models.CharField(choices=[('WHOLE', '整租'), ('SHARED', '合租'), ('COMMERCIAL', '商铺')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.CharField(max_length=80)),
                ('floor', models.IntegerField()),
                ('totalFloors', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('AVAILABLE', '待租'), ('RENTED', '已租'), ('MAINTENANCE', '维护中')], default='AVAILABLE', max_length=20)),
                ('images', models.JSONField(blank=True, default=list)),
                ('facilities', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
