# Generated by Django 5.2.15 on 2026-06-15 16:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('monthlyRent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paymentCycle', models.CharField(choices=[('MONTHLY', '月付'), ('QUARTERLY', '季付'), ('YEARLY', '年付')], default='MONTHLY', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', '待签'), ('ACTIVE', '生效'), ('EXPIRING_SOON', '即将到期'), ('EXPIRED', '已到期'), ('TERMINATED', '已终止')], default='PENDING', max_length=20)),
                ('terminationReason', models.CharField(blank=True, max_length=255)),
                ('landlordSigned', models.BooleanField(default=False)),
                ('tenantSigned', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_leases', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='property.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_leases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
